# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sections"
client_id = "36bd69f223ca1e6deb85537708964d45"
application_url = "https://sections-two-pi.vercel.app/admin"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_themes,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [
  "https://sections-two-pi.vercel.app/api/auth/callback"
]
